sudo: false

language: node_js

before_install:
    - etc/scripts/travis.sh

node_js: 
    - "node"

before_script:
    - export PATH=$PATH:$PWD/out/compilers/ghc/bin
    - export PATH=$PATH:$PWD/out/compilers/gdc/x86_64-pc-linux-gnu/bin
    - export PATH=$PATH:$PWD/out/compilers/rust/bin

script:
    - npm test
    - make travis-dist

deploy:
    provider: s3
    bucket: "compiler-explorer"
    skip_cleanup: true
    acl: public_read
    local_dir: out/dist-bin
    upload-dir: dist/travis/${TRAVIS_BRANCH}
