---
maxTopIcons: 3
levels:
  - name: Corporate Sponsors
    description: 'Enormous thanks to our corporate sponsors. Please visit their websites below:'
    class: corporate
    sponsors:
      - name: Solid Sands
        description: The one-stop shop for C and C++ compiler and library testing, validation and safety services.
        img: https://static.ce-cdn.net/SOLID+SANDS-LOGO-RGB-500px.png
        url: https://solidsands.com/
        priority: 100
        topIconShowEvery: 3
        statsId: solid_sands
      - name: Intel
        description: We engineer solutions for our customers’ greatest challenges with reliable, cloud to edge computing, inspired by Moore’s Law.
        icon: https://static.ce-cdn.net/intel/logo-classicblue-3000px-single-colour.png
        img: https://static.ce-cdn.net/intel/logo-classicblue-3000px.png
        url: https://intel.com/
        priority: 400
        topIconShowEvery: 1
        sideBySide: true
        statsId: intel
      - name: Backtrace
        description:
          - Deliver uninterrupted experiences by automating your response to player-impacting errors. Get started for free.
          - Capture, prioritize, and resolve errors and crashes automatically for uninterrupted user experiences. Get started for free.
        icon: https://static.ce-cdn.net/bt/Black-BT-Logo-A.svg
        icon_dark: https://static.ce-cdn.net/bt/White-BT-Logo-A.svg
        img: https://static.ce-cdn.net/bt/BT-logo (1).png
        url: https://backtrace.io/sign-up?utm_source=website&utm_medium=paiddisplay&utm_campaign=00O8Y000008JiuiUAC&utm_content=godboltbannerad
        priority: 500
        topIconShowEvery: 3
        sideBySide: true
        statsId: backtrace
  - name: Patreon Legends
    description: 'These amazing people have pledged at the highest level of support. Huge thanks to these fine folks:'
    class: legendary
    sponsors:
      - name: Ólafur Waage
        url: https://twitter.com/olafurw
      - name: Aras Pranckevičius
        url: https://aras-p.info/
      - name: Stefan Hagen
        url: https://stefan-hagen.website/
      - name: Robert Douglas
        url: https://www.youtube.com/channel/UCxwGBrWeIIWO9V_uLwRWCdA/videos
      - Igor Zarzycki
      - TocarIP
      - name: Jane Lusby
        url: https://rustbeginners.github.io/awesome-rust-mentors/
      - Corey Kosak
      - name: Ondra Karlik
        url: https://cgg.mff.cuni.cz/~jaroslav/
        description: In memory of Jaroslav Křivánek
      - name: Matthew Guidry
        url: https://blog.matthewguidry.dev/
      # Person with the initials "WB" prefers to remain anonymous
      - name: Casey Carter
      - name: Ben Barbour
      - name: Embark Studios
        url: https://www.embark-studios.com/
      - name: C++Builder
        description: Discover C++Builder
        url: https://www.embarcadero.com/products/cbuilder
      - Kade Phillips
      - Brendan Bellows
      - Daniel Williams
      - name: Paul Williams
        url: https://pcwilliams.design/
      - name: Molecular Matters GmbH
        url: https://liveplusplus.tech/
      - Rui Ueyama
      - name: Rohan Verma
        url: https://twitter.com/rohan_devarc
  - name: Patreons
    description: 'Thanks to all my patrons:'
    sponsors:
      - Karl
      - Matthew Butler
      - Gareth Lloyd
      - Arne Mertz
      - Peter Bindels
      - Slobodan Milnovic
      - Martin
      - Sylvain Joubert
      - Nathan Bronson
      - Kaz Tros
      - Jean-François
      - Charles Wilkes
      - Kaido Kert
      - Carsten Schultz
      - Cornel Izbasa
      - Stefan Groth
      - Sorin Suciu
      - Andreas Gravgaard Andersen
      - Nathan Myers
      - Eugene Nemchenko
      - Bill Caputo
      - Christoph Siedentop
      - Dendi Suhubdy
      - Ilya F.
      - Bastian Kauschke
      - Youngsuk Kim
      - Trent Nelson
      - Guts
      - Noel Cower
      - Alina Banerjee
      - Jean-Luc Burhop
      - Detlef Grohs
      - Phil Burr
      - Mike Babb
      - Matias Christensen
      - Siddhant Nadkarni
      - Emyr Williams
      - Ed Rochenski
      - William Wold
      - Juan Gómez
      - Christopher Koschack
      - Björn Fahller
      - Michael Pearce
      - Solid Sands
      - William Woodall
      - Stefan Petersen
      - Jason Lovett
      - Tomas Dittmann
      - Cory Benfield
      - Tyler Hou
      - Austin Morton
      - William Andersen
      - Joseph Malle
      - Chris Marchetti
      - Ian Cullinan
      - Devon Richard
      - Greg Miller
      - Heinz N. Gies
      - Alison Chaiken
      - David Capello
      - Amos Wenger
      - Kacper Kolodziej
      - Tony Magro
      - Morten Brenna
      - Jake Arkinstall
      - ghochee
      - Shane Clifford
      - Eduardo Costa
      - Ryan Sims
      - Dmytro Lytovchenko
      - Wraithan McCarroll
      - Jean-Simon Lapointe
      - David C Black
      - Venkatesh Srinivas
      - Ruslan Abdikeev
      - Benjamin Demick
      - Reiner Eiteljoerge
      - Johnathan Roatch
      - John Biesnecker
      - CB Bailey
      - Joe Doyle
      - Jason Rice
      - Narut Sereewattanawoot
      - Travis Geiselbrecht
      - Chris Kennelly
      - Tom Hulton-Harrop
      - Adenilson Cavalcanti
      - Wojciech Bartnik
      - Richard Powell
      - Hayk Karapetyan
      - Colden Cullen
      - Josh Seba
      - Matt Pharr
      - Ajay Agrawal
      - Dog Junko
      - Robert Bigelow
      - Lewis Cowles
      - Yuri Kunde Schlesner
      - Glen Fernandes
      - Richard Smith
      - Keith Bennett
      - Herman Polloni
      - Simon Parker
      - Andrew McKinlay
      - Adam Badura
      - Max Langhof
      - Ben Gras
      - Alexandre Baiao
      - Daniel Nissenbaum
      - Gynvael
      - Mikhail Smirnov
      - Mike Cowan
      - paercebal
      - ThePhD
      - Michał Bartoszkiewicz
      - James Clarke
      - Kalyankumar Ramaseshan
      - Pierre-Marie Charavel
      - Brian L. Troutwine
      - -Y-
      - Graham Carl Evans
      - Frank Leon Rose
      - Nathan Burles
      - Tianyu Ge
      - Kale Blankenship
      - Erik Lundin
      - Matt Weber
      - Marcin # dmz1978
      - Laurențiu Nicola
      - Joe Ranweiler
      - modocache
      - Shao Voon
      - Paul Groke # swampmonster9
      - Travis Wehrman
      - Shivanker Goel
      - Hana Dusíková
      - Chris Warner
      - Evan Rowley
      - Glenn
      - Alexander Guettler
      - Alejandro Lucena
      - xyx
      - Chris Luke
      - Adam Greig
      - Eric Perko
      - Christopher Di Bella
      - William Killian
      - Matt Hargett
      - Jeff Trull
      - John McFarlane
      - Jaewon Jung
      - Garret Kelly
      - Dan Luu
      - Tim Cool
      - Jerry Ryle
      - ileonte
      - Matt Weber
      - Simon Haegler
      - Jon Kalb
      - Reuben Scratton
      - Gaëtan Barel
      - Zhihao Yuan
      - David Jones
      - relgukxilef
      - Markus Lanner
      - Igor Ivanov
      - Thomas Trummer
      - Andy Bond
      - Michael Spencer
      - Dmitry Kozhevnikov
      - David Starr
      - Nejc Vivod
      - Thomas Goyne
      - Federico Lebron
      - François Andrieux
      - Mark Atkinson
      - Thomas Pape
      - Robin Jubber
      - Laurynas Biveinis
      - Robert Snell
      - Michał Dominiak
      - Chris Newland
      - Miguel Escudero
      - Ian Carroll
      - Jonathan Anderson
      - Vimarsh Raina
      - Gabriel Garcia
      - Malcolm Rowe
      - Jon Raymond
      - Bene
      - Billy
      - Stefan Wüthrich
      - Yin Zhong
      - Dan Raviv
      - Yacob Cohen-Arazi
      - Tobias Ribizel
      - Joel Falcou
      - Dylan Houlihan
      - Chris Lincoln
      - Josko Nikolic
      - Cody Browne
      - Andrey Oleynikov
      - Karl Bunch
      - Mark Hamann
      - Eric Niebler
      - Richard Ketchersid
      - Victor Ciura
      - Panos Gourgaris
      - Arsen Tufankjian
      - Lesley Lai
      - Federico Zuccardi Merli
      - Andrew Tridgell
      - Jeff Roberts
      - Pankaj Raghav
      - Fredrik Berggren
      - Christoph Siedentop
      - Jeff Dash
      - Borislav Stanimirov
      - Joshua Norrid
      - Nathan Harris
      - Aleksandr Susha
      - Anton Kovalev
      - Luke D
      - Erich Keane
      - Michael Daum
      - Mac Reiter
      - Petr Leonov
      - Niall Cooling
      - Ian
      - Carlos Galán
      - Jake Hemstad
      - Conor Hoekstra
      - Thomas Kristensen
      - Jean-Daniel Deschênes
      - Cypher Signal
      - chad royal
      - Reto Kramer
      - SEG BRK
      - JR Smith
      - Zeke Templin
      - Christoffer
      - Осипов Георгий Андреевич
      - Tomas Michalik
      - Volker Hantschel
      - Ashwin Sawant
      - Amin Aramoon
      - Jason Orendorff
      - Walrus
      - Nicholas Bellamy
      - Emily A. Bellows
      - tattarattat
      - Karsten Opdal
      - Uğur Koltuk
      - Christian Roese
      - Bronek Kozicki
      - Nasztanovics Ferenc
      - grenewode
      - Kevin Solorio
      - Michael Pettit
      - Vaughn Cato
      - David Tracy
      - James Greenhaigh
      - Patrick Hodoul
      - dat
      - Bas Groothedde
      - Marcin Zukowski
      - Anirudha Kumar
      - Amy M
      - Alexander Batashev
      - Nicholas Corgan
      - Dmitri Vedenko
      - Bill Baker
      - John Reagan
      - Oskar Weigl
      - jesyspa
      - Harold Godwinson
      - Dean
      - Robert Bernstein
      - Nathaniel Niles
      - james
      - Keith Jeffery
      - Nico L'Insalata
      - James Wilcox
      - Jonas Greitemann
      - Andrew Spencer
      - Nathan Lawrence
      - Barry Brown
      - Jan Stoltenberg-Lerche
      - Angus Hewlett
      - Joshua
      - Vladimir Motyka
      - Gerasimos Chourdakis
      - Dusan Jovanovic
      - Geoff Evans
      - Pat Monaghan
      - NoNae
      - Martin Weitzel
      - Scott Bruce
      - Sergii Lovygin
      - Marton Szasz
      - CiotatSoft
      - Tadej P
      - Adam Byrd
      - Jonathan Watmough
      - Neil Bickford
      - Unstillable
      - cedric chanoine
      - Cristian Kocza
      - Benji Smith
      - John Mertus
      - Nick Darnell
      - Cordell Bloor
      - Daniele Salvatore Albano
      - Frank Wessels
      - Michele Bianchi
      - Chandler Carruth
      - Daniel Collin
      - Deirdre Connolly
      - Devin Alexander Torres
      - Frede
      - Geert Jansen
      - Greg Bowyer
      - Jaepil Jeong
      - Jakob P. Liljenberg
      - Javier Alvarez
      - Jon Gjengset
      - Komari Spaghetti
      - L. A. F. Pereira
      - Martin Hořeňovský
      - Michael Ford
      - Michael Sartain
      - Patricia Aas
      - Rasmus
      - Siyuan Han
      - Vezel
      - lcnr
      - Abhishek Bhrushundi
      - Jacob Van Buren
      - Martin Ertsås
      - Ryan Zurrin
      - Jason Jack Tan
      - Kim Walisch
      - furl
      - Gwendolyn Hunt

